
export const STOCKS: string[] = [
    "RELIANCE:NSE", "TCS:NSE", "HDFCBANK:NSE", "INFY:NSE",
    "ICICIBANK:NSE", "HINDUNILVR:NSE", "SBIN:NSE", "BHARTIARTL:NSE",
    "ITC:NSE", "LT:NSE", "KOTAKBANK:NSE", "WIPRO:NSE"
];

export const REFRESH_INTERVAL_SECONDS = 60;